// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oybxlwmdnppwiyjxclau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95Ynhsd21kbnBwd2l5anhjbGF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMDgwNTUsImV4cCI6MjA2MDY4NDA1NX0.uJbhjYZ3XEqUsWWh-vmQzhlLldsQlxSZjSpAilh12bA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);